Add some slack notifications

diff --git a/.github/workflows/environment-test2.yml b/.github/workflows/environment-test2.yml
--- a/.github/workflows/environment-test2.yml
+++ b/.github/workflows/environment-test2.yml
@@ -1,8 +1,8 @@
-name: Environment test
+name: Environment test2
 on:
   push:
     tags:
-      - 'test-*'
+      - 'test2-*'
 
 jobs:
   notify:
@@ -14,16 +14,34 @@ jobs:
     steps:
       - name: Get vars
         id: vars
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
         run: |
           echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
+
+          JSON="$(curl -v --fail -L \
+            --request GET \
+            --header "authorization: Bearer $API_TOKEN_GITHUB" \
+            --url "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/environments/test2" 
+          )"
+          TIMER="$(jq -e '.protection_rules[] | select( .type == "wait_timer" ) | .wait_timer' <<<"$JSON")"
+          if [[ ! "$TIMER" =~ ^[0-9]+$ ]]; then
+            echo "::error::Wait timer is not set for environment test2"
+            exit 1
+          elif [[ $TIMER -lt 10 ]]; then
+            echo "::error::Timer is too short, set to $TIMER but minimum is 10"
+            exit 1
+          else
+            echo "::set-output name=timer::$TIMER"
+          fi
 
       - name: Notify in Slack
         uses: slackapi/slack-github-action@v1.15.0
         with:
           channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
           slack-message: >
-            Tag [${{ steps.vars.outputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.vars.outputs.tag }}) of ${{ github.repository }} is ready to deploy!
-            Approvers, [go review it!](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
+            Tag [${{ steps.vars.outputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.vars.outputs.tag }}) of ${{ github.repository }} will be deployed in ${{ steps.vars.outputs.timer }} minutes!
+            [Review this deployment](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
         env:
           SLACK_BOT_TOKEN: ${{ SLACK_TOKEN }}
 
@@ -32,7 +50,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: notify
     environment:
-      name: test
+      name: test2
       url: https://github.com/${{ github.repository }}/releases/tag/${{ needs.notify.outputs.tag }}
 
     steps:
